language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r-packages:
- shape 
- colorspace
- RColorBrewer
- testthat
- knitr
- markdown
- dendextend
- covr
- GetoptLong
- GlobalOptions

bioc_packages:
- GenomicRanges
- HilbertVis
- ComplexHeatmap
- HilbertCurve

r_check_args: --no-vignettes --no-build-vignettes

r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
  
