# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: true
r:
  - oldrel
  - release
  - devel
env:
  global:
    - NOT_CRAN=false
addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libgdal1-dev
      - libproj-dev
before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = list("R/skim_print.R" = c(147, 167, 178:180, 190)))'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    tags: true
