# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
cache: packages

addons:
  apt:
    packages:
      - xsel

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

services:
  - xvfb

matrix:
  include:
    - r: devel
    - r: release
      after_success:
      - Rscript -e 'covr::codecov()'
      - find . -name testthat.Rout | xargs cat
      after_failure:
      - find . -name testthat.Rout | xargs cat
      before_cache:
      - Rscript -e 'remotes::install_cran("pkgdown")'
      - Rscript -e 'remotes::install_github("tidyverse/tidytemplate")'
      - Rscript -e 'remotes::install_cran("dplyr")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
    - r: 3.5
    - r: 3.4
    - r: 3.3
    - r: 3.2
